### ISSUE TITLE
How to make a signal for post-hoc power analysis in paired t-tests

### ISSUE THREAD

**Issue by takedarort** [0todd0000/power1d#4]
Dr. Pataky, Nice to meet you.
I have a question about the post-hoc power analysis using Power1D.

I am testing the reproducibility of sensor data with 101 time points and I have 2 sessions of data for 30 people.
The data from the first and second session did not differ according to the Paired t-test in SPM1d.

I have performed a posteriori power test for this test using the following code.

#########################
J  = 30 # No of subjects
Q  = 101 # time points

data0 = np.loadtxt(file)
first_data = data0[:,0] # mean data in 30 subjects. 1*101 array 
second_data = data0[:,1] # mean data in 30 subjects. 1*101 array 
diff_data = data0[:,2] # diff_data: first_data-second_data
diff_sd = data0[0,3] # standard deviation of diff_data

data_bl = power1d.geom.Null( Q ) # baseline
data0_sig0  = power1d.geom.Null( Q ) # null signal - needed for null power model
data0_sig1  = power1d.geom.Continuum1D( diff_data ) #signal
data0_nse    = power1d.noise.SmoothGaussian( J , Q , mu = 0 , sigma = diff_sd , fwhm = 20 ) #Noise
data0_mod0   = power1d.models.DataSample( data0_bl, data_sig0, data0_nse, J ) # null for power analysis
data0_mod1   = power1d.models.DataSample( data0_bl, data_sig1, data0_nse, J ) # alternative

power_analysis(data0_mod0,data0_mod1)
########################

According to your papter in J of Biomech.(doi: 10.1016/j.jbiomech.2021.110451.) 
and its supplementary code (https://github.com/m-a-robinson/sample-size/blob/main/creating_1d_effects.py),
you made the data_sig1 using GaussianPulse objects.

Since my analysis is a post-hoc power analysis and we already know the mean data to be compared,
I made the data0_sig1 as a Continuum1D objects containing the difference data between 1st and 2nd sessions.
It it appropreate procedure?

I would appreciate it if you could help me.

**Comment by 0todd0000** [comment]
This approach seems appropriate in general, but I'd also recommend using the `fwhm` value that is estimated from the experimental data.  You can get the estimated FWHM as the `fwhm` attributed of the SPM object returned by all **spm1d.stats** procedures. For example:

```python
spm = spm1d.stats.ttest2(y1, y0)
print( spm.fwhm )
```


<br>
<br>

As an aside, some regard *a posteriori* power analysis as flawed because it can be antithetical to the *a priori* nature of power analysis. Experimental means are inherently random, so the main idea is that (random) experimental means cannot represent an hypothesized effect. Regardless of the controversy / debate regarding *a posteriori* power analyses, if you do intend to report *a posteriori* power results I suggest stating that the study was exploratory and that there was therefore no *a priori* hypothesis upon which *a priori* power analyses could have been conducted. Clearly indicating the exploratory nature of the study should be a suitable justification for review purposes.

**Comment by takedarort** [comment]
Thank you for your quick response and kind advices.
